# docker-compose -f docker-compose.yml up -d
# docker-compose up --build
version: "3.9"
services:
  app:
    image: dhrypt/animated-waddle:latest
    container_name: animated-waddle
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - DATABASE_HOST=${POSTGRES_HOST}
      - DATABASE_PORT=${POSTGRES_PORT}
    build: .
    ports:
      - "8085:8085"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - learning

  postgresdb:
    image: dhrypt/animated-waddledb:latest
    container_name: animated-waddledb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - learning

volumes:
  postgres-data:

networks:
  learning:
    driver: bridge
